"""
Convert reduced JSON metric files to Iceberg tables.
Reads JSON files from S3 (generated by multi-thread-spark-metric-enhanced.py)
and writes to Iceberg in batches.

Handles core metrics (49 fields) + summary metrics (6 fields).
Enhanced JSON details removed to reduce file sizes.
"""

import json
import sys
import os
import boto3
import pandas as pd
import pyarrow as pa
from pyiceberg.catalog import load_catalog
from datetime import datetime

################################################################################
# USER CONFIGURATION - Edit these values for your environment
################################################################################
# When you pull Git updates, only this section needs to be reviewed/updated

# ========== REQUIRED: S3 Configuration ==========
# Your S3 bucket where extracted metrics are stored
# Format: spark-history-<account-id>-<region>
# Example: "spark-history-123456789012-us-east-1"
INPUT_BUCKET = os.getenv("S3_BUCKET", "YOUR_S3_BUCKET_HERE")

# S3 prefix for task stage summary JSON files (auto-set by orchestrator)
# Example: "target-metrics/task_stage_summary/"
INPUT_PREFIX_TASK_STAGE = os.getenv("INPUT_PREFIX_TASK_STAGE", "target-metrics/task_stage_summary/")

# S3 prefix for spark config extract JSON files (auto-set by orchestrator)
# Example: "target-metrics/spark_config_extract/"
INPUT_PREFIX_CONFIG = os.getenv("INPUT_PREFIX_CONFIG", "target-metrics/spark_config_extract/")

# ========== REQUIRED: Hive Metastore Configuration ==========
# Hive Metastore URI for Iceberg catalog
# Format: thrift://<hms-hostname>:<port>
# Example: "thrift://hms.example.com:9083" or "thrift://localhost:9083"
HMS_URI = os.getenv("HMS_URI", "thrift://YOUR_HMS_HOST:9083")

# Enable SSL for HMS connection (true/false)
HMS_USE_SSL = os.getenv("HMS_USE_SSL", "false").lower() == "true"

# ========== Iceberg Table Configuration ==========
# Iceberg catalog name (usually "hive" for HMS-based catalogs)
ICEBERG_CATALOG_NAME = os.getenv("ICEBERG_CATALOG_NAME", "hive")

# Database/schema name where tables are located
# Example: "data_processing"
ICEBERG_NAMESPACE = os.getenv("ICEBERG_NAMESPACE", "data_processing")

# Table names for metrics (without database prefix)
ICEBERG_TABLE_TASK_STAGE = os.getenv("ICEBERG_TABLE_TASK_STAGE", "spark_metrics_task_stage_v2")
ICEBERG_TABLE_CONFIG = os.getenv("ICEBERG_TABLE_CONFIG", "spark_metrics_config_v2")

# ========== Optional: AWS Settings ==========
# AWS CLI profile name (leave as None to use default credentials or instance role)
AWS_PROFILE = os.environ.get('AWS_PROFILE') or None

# STS Role ARN for cross-account S3 access (optional, leave empty if not needed)
# Example: "arn:aws:iam::123456789012:role/MyRole" or ""
ASSUME_ROLE_ARN = os.getenv("ASSUME_ROLE_ARN", "")

# ========== Processing Configuration ==========
# Batch size for processing JSON files
BATCH_SIZE = 100

# ========== Validation ==========
if INPUT_BUCKET == "YOUR_S3_BUCKET_HERE" or not INPUT_BUCKET:
    raise ValueError(
        "\n" + "="*80 + "\n"
        "ERROR: INPUT_BUCKET (S3_BUCKET) must be configured!\n"
        "Please edit line 29 of this script and set your S3 bucket name.\n"
        "Example: INPUT_BUCKET = 'spark-history-123456789012-us-east-1'\n"
        "="*80
    )

if "YOUR_HMS_HOST" in HMS_URI or not HMS_URI:
    raise ValueError(
        "\n" + "="*80 + "\n"
        "ERROR: HMS_URI must be configured!\n"
        "Please edit line 42 of this script and set your Hive Metastore URI.\n"
        "Example: HMS_URI = 'thrift://hms.example.com:9083'\n"
        "="*80
    )

################################################################################
# END OF USER CONFIGURATION
# Do not modify below this line unless you know what you're doing
################################################################################


def get_s3_client(profile=None):
    session = boto3.Session(profile_name=profile) if profile else boto3.Session()
    return session.client('s3')


def get_s3_credentials(profile=None, role_arn=None):
    """Get S3 credentials for PyIceberg - tries STS assume-role first, falls back to profile credentials"""
    session = boto3.Session(profile_name=profile) if profile else boto3.Session()

    # Try STS assume-role first
    if role_arn:
        try:
            sts = session.client('sts')
            response = sts.assume_role(
                RoleArn=role_arn,
                RoleSessionName="pyiceberg-hms-session",
                DurationSeconds=3600
            )
            creds = response['Credentials']
            print(f"✓ Assumed role: {role_arn}")
            print(f"  Session expires: {creds['Expiration']}")
            return {
                "s3.access-key-id": creds['AccessKeyId'],
                "s3.secret-access-key": creds['SecretAccessKey'],
                "s3.session-token": creds['SessionToken'],
            }
        except Exception as e:
            print(f"  ⚠ Could not assume role {role_arn}: {e}")
            print(f"  Falling back to profile credentials...")

    # Fallback: use profile's own credentials
    credentials = session.get_credentials()
    if credentials:
        frozen = credentials.get_frozen_credentials()
        cred_dict = {
            "s3.access-key-id": frozen.access_key,
            "s3.secret-access-key": frozen.secret_key,
        }
        if frozen.token:
            cred_dict["s3.session-token"] = frozen.token
        print(f"✓ Using profile credentials: {profile or 'default'}")
        return cred_dict

    print("  ⚠ No credentials found — PyIceberg will use default credential chain")
    return {}


def list_s3_files(bucket: str, prefix: str, profile=None):
    """List all JSON files in S3 prefix"""
    s3_client = get_s3_client(profile)
    files = []
    paginator = s3_client.get_paginator('list_objects_v2')
    pages = paginator.paginate(Bucket=bucket, Prefix=prefix)
    for page in pages:
        if 'Contents' in page:
            for obj in page['Contents']:
                key = obj['Key']
                if key.endswith('.json') and not key.endswith('/'):
                    files.append(key)
    return files


def read_json_from_s3(bucket: str, key: str, profile=None):
    """Read and parse JSON file from S3"""
    s3_client = get_s3_client(profile)
    try:
        response = s3_client.get_object(Bucket=bucket, Key=key)
        content = response['Body'].read().decode('utf-8')
        return json.loads(content)
    except Exception as e:
        print(f"Error reading {key}: {e}")
        return None


def flatten_enhanced_for_iceberg(data: dict) -> dict:
    """Flatten enhanced nested dictionary for Iceberg table with proper type casting"""
    flat = {}

    # Helper to safely convert to float
    def to_float(val):
        if val is None:
            return None
        try:
            return float(val)
        except (ValueError, TypeError):
            return None

    # Helper to safely convert to int (for LONG columns)
    def to_int(val):
        if val is None:
            return None
        try:
            return int(val)
        except (ValueError, TypeError):
            return None

    # Top-level fields (1-11)
    flat['application_id'] = data.get('application_id')
    flat['extraction_timestamp'] = data.get('extraction_timestamp')
    flat['event_count'] = to_int(data.get('event_count'))  # LONG type
    
    # Application info
    app_info = data.get('application_info', {})
    flat['job_id'] = app_info.get('job_id')
    flat['cluster_id'] = app_info.get('cluster_id')
    flat['application_name'] = app_info.get('application_name')
    flat['app_id'] = app_info.get('app_id')
    flat['application_start_time'] = app_info.get('application_start_time')
    flat['application_end_time'] = app_info.get('application_end_time')
    flat['total_run_duration_minutes'] = to_float(app_info.get('total_run_duration_minutes'))
    flat['total_run_duration_hours'] = to_float(app_info.get('total_run_duration_hours'))
    
    # Task summary (12-16)
    task = data.get('task_summary', {})
    flat['task_total_tasks'] = task.get('total_tasks')
    flat['task_completed_tasks'] = task.get('completed_tasks')
    flat['task_failed_tasks'] = task.get('failed_tasks')
    flat['task_killed_tasks'] = task.get('killed_tasks')
    flat['task_success_rate_percent'] = to_float(task.get('success_rate_percent'))
    
    # Stage summary (17-21) - convert counts to LONG (int64)
    stage = data.get('stage_summary', {})
    flat['stage_total_stages'] = to_int(stage.get('total_stages'))  # LONG type
    flat['stage_completed_stages'] = to_int(stage.get('completed_stages'))  # LONG type
    flat['stage_failed_stages'] = to_int(stage.get('failed_stages'))  # LONG type
    flat['stage_skipped_stages'] = to_int(stage.get('skipped_stages'))  # LONG type
    flat['stage_success_rate_percent'] = to_float(stage.get('success_rate_percent'))
    
    # Executor summary (22-33) - ensure all are floats
    executor = data.get('executor_summary', {})
    flat['executor_total_executors'] = executor.get('total_executors')
    flat['executor_active_executors'] = executor.get('active_executors')
    flat['executor_avg_memory_utilization_percent'] = to_float(executor.get('avg_memory_utilization_percent'))
    flat['executor_min_memory_utilization_percent'] = to_float(executor.get('min_memory_utilization_percent'))
    flat['executor_max_memory_utilization_percent'] = to_float(executor.get('max_memory_utilization_percent'))
    flat['executor_median_memory_utilization_percent'] = to_float(executor.get('median_memory_utilization_percent'))
    flat['executor_avg_cpu_utilization_percent'] = to_float(executor.get('avg_cpu_utilization_percent'))
    flat['executor_min_cpu_utilization_percent'] = to_float(executor.get('min_cpu_utilization_percent'))
    flat['executor_max_cpu_utilization_percent'] = to_float(executor.get('max_cpu_utilization_percent'))
    flat['executor_median_cpu_utilization_percent'] = to_float(executor.get('median_cpu_utilization_percent'))
    flat['executor_total_cost_factor'] = to_float(executor.get('total_cost_factor'))
    flat['executor_details'] = json.dumps(executor.get('executor_details', []))
    
    # I/O summary (34-49) - ensure all are floats
    io = data.get('io_summary', {})
    # Handle nested structure - io_summary might have application_level
    if 'application_level' in io:
        io = io['application_level']
    
    flat['io_total_input_gb'] = to_float(io.get('total_input_gb'))
    flat['io_total_output_gb'] = to_float(io.get('total_output_gb'))
    flat['io_total_shuffle_read_gb'] = to_float(io.get('total_shuffle_read_gb'))
    flat['io_total_shuffle_write_gb'] = to_float(io.get('total_shuffle_write_gb'))
    flat['io_input_per_task_min_gb'] = to_float(io.get('input_per_task_min_gb'))
    flat['io_input_per_task_max_gb'] = to_float(io.get('input_per_task_max_gb'))
    flat['io_input_per_task_avg_gb'] = to_float(io.get('input_per_task_avg_gb'))
    flat['io_input_per_task_median_gb'] = to_float(io.get('input_per_task_median_gb'))
    flat['io_shuffle_read_per_task_min_gb'] = to_float(io.get('shuffle_read_per_task_min_gb'))
    flat['io_shuffle_read_per_task_max_gb'] = to_float(io.get('shuffle_read_per_task_max_gb'))
    flat['io_shuffle_read_per_task_avg_gb'] = to_float(io.get('shuffle_read_per_task_avg_gb'))
    flat['io_shuffle_read_per_task_median_gb'] = to_float(io.get('shuffle_read_per_task_median_gb'))
    flat['io_shuffle_write_per_task_min_gb'] = to_float(io.get('shuffle_write_per_task_min_gb'))
    flat['io_shuffle_write_per_task_max_gb'] = to_float(io.get('shuffle_write_per_task_max_gb'))
    flat['io_shuffle_write_per_task_avg_gb'] = to_float(io.get('shuffle_write_per_task_avg_gb'))
    flat['io_shuffle_write_per_task_median_gb'] = to_float(io.get('shuffle_write_per_task_median_gb'))
    
    # Top-level cost (50)
    flat['total_cost_factor'] = to_float(data.get('total_cost_factor'))
    
    # Spill Summary (51-54) - Always include these fields
    spill = data.get('spill_summary', {})
    flat['spill_total_memory_spilled_gb'] = to_float(spill.get('total_memory_spilled_gb'))
    flat['spill_total_disk_spilled_gb'] = to_float(spill.get('total_disk_spilled_gb'))
    flat['spill_tasks_with_memory_spill_percent'] = to_float(spill.get('tasks_with_memory_spill_percent'))
    flat['spill_tasks_with_disk_spill_percent'] = to_float(spill.get('tasks_with_disk_spill_percent'))
    
    # REMOVED: Enhanced metrics as JSON strings (50-66) to reduce file sizes
    # These detailed JSON fields are no longer extracted to keep output manageable
    
    # Summary metrics from enhanced categories (55-60) - extracted from nested data
    # Cast to float (double) for table compatibility
    job_details = data.get('job_details', {})
    job_summary = job_details.get('summary', {}) if isinstance(job_details, dict) else {}
    flat['job_total_jobs'] = to_float(job_summary.get('total_jobs'))
    flat['job_successful_jobs'] = to_float(job_summary.get('successful_jobs'))
    flat['job_failed_jobs'] = to_float(job_summary.get('failed_jobs'))

    sql_metrics = data.get('sql_metrics', {})
    flat['sql_total_executions'] = to_float(sql_metrics.get('total_sql_executions')) if isinstance(sql_metrics, dict) else None

    driver_metrics = data.get('driver_metrics', {})
    flat['driver_total_tasks_launched'] = to_float(driver_metrics.get('total_tasks_launched')) if isinstance(driver_metrics, dict) else None
    flat['driver_memory_utilization_percent'] = to_float(driver_metrics.get('memory_utilization_percent')) if isinstance(driver_metrics, dict) else None
    
    return flat


def flatten_config_for_iceberg(data: dict) -> dict:
    """Flatten config data for Iceberg with additional config fields"""
    spark_config = data.get('spark_configuration', {})
    
    return {
        'application_id': data.get('application_id'),
        'extraction_timestamp': data.get('extraction_timestamp'),
        'cluster_id': data.get('cluster_id'),
        'job_id': data.get('job_id'),
        'application_name': data.get('application_name'),
        'app_id': data.get('app_id'),
        'application_start_time': data.get('application_start_time'),
        'application_end_time': data.get('application_end_time'),
        'total_run_duration_minutes': data.get('total_run_duration_minutes'),
        'total_run_duration_hours': data.get('total_run_duration_hours'),
        'total_cost_factor': data.get('total_cost_factor'),
        'spark_executor_cores': spark_config.get('spark.executor.cores'),
        'spark_executor_memory': spark_config.get('spark.executor.memory'),
        'spark_executor_instances': spark_config.get('spark.executor.instances'),
        'spark_dynamic_allocation_enabled': spark_config.get('spark.dynamicAllocation.enabled'),
        'spark_sql_shuffle_partitions': spark_config.get('spark.sql.shuffle.partitions'),
        'spark_sql_files_max_partition_bytes': spark_config.get('spark.sql.files.maxPartitionBytes'),
        'spark_driver_cores': spark_config.get('spark.driver.cores'),
        'spark_driver_memory': spark_config.get('spark.driver.memory'),
        'spark_dynamic_allocation_min_executors': spark_config.get('spark.dynamicAllocation.minExecutors'),
        'spark_dynamic_allocation_max_executors': spark_config.get('spark.dynamicAllocation.maxExecutors'),
    }


def write_to_iceberg(catalog, table_name: str, records: list, valid_columns: set = None):
    """Write records to Iceberg table, filtering to only valid columns"""
    if not records:
        return

    try:
        table = catalog.load_table(f"{ICEBERG_NAMESPACE}.{table_name}")
        df = pd.DataFrame(records)

        # Filter to only columns that exist in the table schema
        if valid_columns:
            extra_cols = set(df.columns) - valid_columns
            if extra_cols:
                print(f"  ⚠ Dropping {len(extra_cols)} columns not in table: {', '.join(sorted(extra_cols)[:5])}{'...' if len(extra_cols) > 5 else ''}")
                df = df[[col for col in df.columns if col in valid_columns]]

        # Explicitly cast numeric columns for task_stage_summary
        if table_name == ICEBERG_TABLE_TASK_STAGE:
            # Cast these fields to int64 (long) - they represent counts
            int_columns = [
                'event_count',
                'stage_completed_stages',
                'stage_failed_stages',
                'stage_skipped_stages',
                'stage_total_stages',
                'task_total_tasks',
                'task_completed_tasks',
                'task_failed_tasks',
                'task_killed_tasks',
                'executor_total_executors',
                'executor_active_executors'
            ]
            for col in int_columns:
                if col in df.columns:
                    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype('int64')

            # Cast these fields to float64 (double)
            float_columns = [
                'total_run_duration_minutes', 'total_run_duration_hours',
                'task_success_rate_percent', 'stage_success_rate_percent',
                'executor_avg_memory_utilization_percent', 'executor_min_memory_utilization_percent',
                'executor_max_memory_utilization_percent', 'executor_median_memory_utilization_percent',
                'executor_avg_cpu_utilization_percent', 'executor_min_cpu_utilization_percent',
                'executor_max_cpu_utilization_percent', 'executor_median_cpu_utilization_percent',
                'executor_total_cost_factor',
                'io_total_input_gb', 'io_total_output_gb', 'io_total_shuffle_read_gb', 'io_total_shuffle_write_gb',
                'io_input_per_task_min_gb', 'io_input_per_task_max_gb', 'io_input_per_task_avg_gb',
                'io_input_per_task_median_gb', 'io_shuffle_read_per_task_min_gb', 'io_shuffle_read_per_task_max_gb',
                'io_shuffle_read_per_task_avg_gb', 'io_shuffle_read_per_task_median_gb',
                'io_shuffle_write_per_task_min_gb', 'io_shuffle_write_per_task_max_gb',
                'io_shuffle_write_per_task_avg_gb', 'io_shuffle_write_per_task_median_gb',
                'total_cost_factor', 'driver_memory_utilization_percent',
                'spill_total_memory_spilled_gb', 'spill_total_disk_spilled_gb',
                'spill_tasks_with_memory_spill_percent', 'spill_tasks_with_disk_spill_percent',
                'job_total_jobs', 'job_successful_jobs', 'job_failed_jobs',
                'sql_total_executions', 'driver_total_tasks_launched'
            ]
            for col in float_columns:
                if col in df.columns:
                    df[col] = pd.to_numeric(df[col], errors='coerce').astype('float64')

        # Convert pandas DataFrame to PyArrow Table
        arrow_table = pa.Table.from_pandas(df)

        # Make application_id non-nullable to match Iceberg schema
        schema = arrow_table.schema
        new_fields = []
        for field in schema:
            if field.name == 'application_id':
                new_fields.append(pa.field(field.name, field.type, nullable=False))
            else:
                new_fields.append(field)

        new_schema = pa.schema(new_fields)
        arrow_table = arrow_table.cast(new_schema)

        table.append(arrow_table)
        print(f"  ✓ Wrote {len(records)} records to {table_name}")
    except Exception as e:
        print(f"  ✗ Error writing to {table_name}: {e}")
        import traceback
        traceback.print_exc()


def extract_job_ids_from_iceberg_input(bucket, prefix_path, profile=None):
    """
    Extract job_ids from spark_config_extract JSON files.
    Reads from spark_config_extract folder to get job_ids from JSON content.
    Returns list of job_ids in order.
    """
    job_ids = []
    s3_client = get_s3_client(profile)

    try:
        # Convert task_stage_summary path to spark_config_extract path
        # From: test-target-metrics/20260331T121921Z/task_stage_summary/
        # To: test-target-metrics/20260331T121921Z/spark_config_extract/
        config_prefix = prefix_path.replace('task_stage_summary', 'spark_config_extract')

        paginator = s3_client.get_paginator('list_objects_v2')
        pages = paginator.paginate(Bucket=bucket, Prefix=config_prefix)

        print(f"\nExtracting job_ids from spark_config_extract files in s3://{bucket}/{config_prefix}")
        for page in pages:
            for obj in page.get('Contents', []):
                key = obj['Key']
                if key.endswith('.json') and not key.endswith('/'):
                    try:
                        body = s3_client.get_object(Bucket=bucket, Key=key)['Body'].read().decode('utf-8')
                        data = json.loads(body)
                        job_id = data.get('job_id')
                        if job_id:
                            job_ids.append(job_id)
                            print(f"  ✓ Found job_id: {job_id}")
                    except Exception as e:
                        print(f"  ⚠ Error reading {key}: {e}")

        print(f"✓ Extracted {len(job_ids)} job_ids total from spark_config_extract")
        return job_ids if job_ids else []

    except Exception as e:
        print(f"✗ Error extracting job_ids: {e}")
        return []


def main(timestamp=None):
    """
    Load JSON metrics from S3 to Iceberg tables.

    Args:
        timestamp: Optional timestamp to filter Step 1 output (e.g., "20260331T095519Z")
                  If provided, reads only files from s3://bucket/test-target-metrics/{timestamp}/
                  If not provided, reads from s3://bucket/test-target-metrics/ (all historical files)
    """
    global INPUT_PREFIX_TASK_STAGE, INPUT_PREFIX_CONFIG

    # Update S3 paths based on timestamp
    if timestamp:
        INPUT_PREFIX_TASK_STAGE = f"test-target-metrics/{timestamp}/task_stage_summary/"
        INPUT_PREFIX_CONFIG = f"test-target-metrics/{timestamp}/spark_config_extract/"
        print(f"Using timestamped paths (only recent 5 applications)")
    else:
        print(f"Using default paths (ALL historical files)")

    print("="*80)
    print("REDUCED JSON TO ICEBERG CONVERTER")
    print("="*80)
    print(f"Task stage input: s3://{INPUT_BUCKET}/{INPUT_PREFIX_TASK_STAGE}")
    print(f"Config input:     s3://{INPUT_BUCKET}/{INPUT_PREFIX_CONFIG}")
    print("\nProcesses core metrics (49 fields) + spill (4 fields) + summary (6 fields)")
    print("Enhanced JSON details removed to reduce file sizes")

    # Initialize catalog
    print("\nInitializing Iceberg catalog (HMS via WaggleDance)...")
    print(f"  HMS URI: {HMS_URI}")

    # Get S3 credentials (tries assume-role, falls back to profile)
    s3_creds = get_s3_credentials(profile=AWS_PROFILE, role_arn=ASSUME_ROLE_ARN)

    catalog = load_catalog(
        ICEBERG_CATALOG_NAME,
        **{
            "type": "hive",
            "uri": HMS_URI,
            "hive.metastore.use-ssl": str(HMS_USE_SSL).lower(),
            **s3_creds,
        }
    )
    print("✓ Catalog ready")
    
    # Check if tables exist and print schema
    print("\nChecking table schemas...")
    table_columns = {}
    try:
        table = catalog.load_table(f"{ICEBERG_NAMESPACE}.{ICEBERG_TABLE_TASK_STAGE}")
        schema_fields = [field.name for field in table.schema().fields]
        table_columns[ICEBERG_TABLE_TASK_STAGE] = set(schema_fields)
        print(f"✓ Table {ICEBERG_TABLE_TASK_STAGE}: {len(schema_fields)} columns")
        print(f"  Columns: {', '.join(schema_fields[:10])}{'...' if len(schema_fields) > 10 else ''}")

        # Check for spill columns (all should be present in v1 schema)
        spill_fields = [
            'spill_total_memory_spilled_gb',
            'spill_total_disk_spilled_gb',
            'spill_tasks_with_memory_spill_percent',
            'spill_tasks_with_disk_spill_percent'
        ]
        present_spill_fields = [f for f in spill_fields if f in schema_fields]
        if len(present_spill_fields) == len(spill_fields):
            print(f"  ✓ All {len(spill_fields)} spill columns present")
        else:
            missing_spill = [f for f in spill_fields if f not in schema_fields]
            print(f"  ⚠ Missing {len(missing_spill)} spill columns (will skip): {', '.join(missing_spill)}")
    except Exception as e:
        print(f"⚠️  Could not load table {ICEBERG_TABLE_TASK_STAGE}: {e}")
        print(f"   Make sure the table exists in namespace '{ICEBERG_NAMESPACE}'")
        print("="*80)
        sys.exit(1)
    
    try:
        config_table = catalog.load_table(f"{ICEBERG_NAMESPACE}.{ICEBERG_TABLE_CONFIG}")
        config_fields = [field.name for field in config_table.schema().fields]
        table_columns[ICEBERG_TABLE_CONFIG] = set(config_fields)
        print(f"✓ Table {ICEBERG_TABLE_CONFIG}: {len(config_fields)} columns")
        print(f"  Columns: {', '.join(config_fields[:10])}{'...' if len(config_fields) > 10 else ''}")
    except Exception as e:
        print(f"⚠️  Could not load table {ICEBERG_TABLE_CONFIG}: {e}")
        print(f"   Config table will be skipped")

    # Initialize job_ids list at function level (not inside if/else)
    # NOTE: job_ids will be extracted from spark_config_extract, not task_stage_summary
    all_job_ids = []  # Track job_ids from spark_config_extract

    # Process task_stage_summary files
    print(f"Processing task_stage_summary files from s3://{INPUT_BUCKET}/{INPUT_PREFIX_TASK_STAGE}")
    task_files = list_s3_files(INPUT_BUCKET, INPUT_PREFIX_TASK_STAGE, AWS_PROFILE)
    print(f"Found {len(task_files)} JSON files")

    if not task_files:
        print("⚠ No task_stage_summary files found!")
    else:
        task_batch = []
        for i, key in enumerate(task_files):
            data = read_json_from_s3(INPUT_BUCKET, key, AWS_PROFILE)
            if data:
                flattened = flatten_enhanced_for_iceberg(data)
                task_batch.append(flattened)

                # DO NOT extract job_ids from task_stage_summary
                # job_ids will be extracted from spark_config_extract files instead

                # Write batch
                if len(task_batch) >= BATCH_SIZE:
                    print(f"\n  Writing batch of {len(task_batch)} records to {ICEBERG_TABLE_TASK_STAGE}")
                    write_to_iceberg(catalog, ICEBERG_TABLE_TASK_STAGE, task_batch, table_columns.get(ICEBERG_TABLE_TASK_STAGE))
                    task_batch.clear()

            if (i + 1) % 10 == 0:
                print(f"  Processed {i + 1}/{len(task_files)} files...")

        # Write remaining
        if task_batch:
            print(f"\n  Writing final batch of {len(task_batch)} records to {ICEBERG_TABLE_TASK_STAGE}")
            write_to_iceberg(catalog, ICEBERG_TABLE_TASK_STAGE, task_batch, table_columns.get(ICEBERG_TABLE_TASK_STAGE))

        print(f"\n✓ Completed task_stage_summary: {len(task_files)} records")
        print()
    
    # Process spark_config_extract files
    if ICEBERG_TABLE_CONFIG not in table_columns:
        print(f"\n⚠ Skipping {ICEBERG_TABLE_CONFIG} — table not loaded")
    else:
        print(f"\nProcessing spark_config_extract files from s3://{INPUT_BUCKET}/{INPUT_PREFIX_CONFIG}")
        config_files = list_s3_files(INPUT_BUCKET, INPUT_PREFIX_CONFIG, AWS_PROFILE)
        print(f"Found {len(config_files)} JSON files")

        if not config_files:
            print("⚠ No spark_config_extract files found!")
        else:
            config_batch = []
            for i, key in enumerate(config_files):
                data = read_json_from_s3(INPUT_BUCKET, key, AWS_PROFILE)
                if data:
                    flattened = flatten_config_for_iceberg(data)
                    config_batch.append(flattened)

                    # Track job_ids being written to Iceberg
                    job_id = flattened.get('job_id')
                    if job_id and job_id not in all_job_ids:
                        all_job_ids.append(job_id)

                    # Write batch
                    if len(config_batch) >= BATCH_SIZE:
                        print(f"\n  Writing batch of {len(config_batch)} records to {ICEBERG_TABLE_CONFIG}")
                        print(f"  Job IDs in this batch: {[rec.get('job_id') for rec in config_batch]}")
                        write_to_iceberg(catalog, ICEBERG_TABLE_CONFIG, config_batch, table_columns.get(ICEBERG_TABLE_CONFIG))
                        config_batch.clear()

                if (i + 1) % 10 == 0:
                    print(f"  Processed {i + 1}/{len(config_files)} files...")

            # Write remaining
            if config_batch:
                print(f"\n  Writing final batch of {len(config_batch)} records to {ICEBERG_TABLE_CONFIG}")
                print(f"  Job IDs in this batch: {[rec.get('job_id') for rec in config_batch]}")
                write_to_iceberg(catalog, ICEBERG_TABLE_CONFIG, config_batch, table_columns.get(ICEBERG_TABLE_CONFIG))

            print(f"\n✓ Completed spark_config_extract: {len(config_files)} records")
            print(f"  Total unique job_ids written: {len(all_job_ids)}")
            if all_job_ids:
                print(f"  Job IDs written to Iceberg:")
                for i, jid in enumerate(all_job_ids, 1):
                    print(f"    {i}. {jid}")
            print()

    print("\n" + "="*80)
    print("EXTRACTION SUMMARY")
    print("="*80)
    print(f"Unique Job IDs extracted from spark_config_extract: {len(all_job_ids)}")
    if all_job_ids:
        for i, jid in enumerate(all_job_ids, 1):
            print(f"  {i}. {jid}")
    print("="*80)

    print("\n" + "="*80)
    print("✓ Enhanced conversion complete!")
    print("="*80)

    # Use job_ids we collected from spark_config_extract while writing (already guaranteed to be in Iceberg table)
    # This is crucial for filtering in downstream steps
    job_ids = all_job_ids if all_job_ids else []

    print(f"\nIceberg tables (HMS via WaggleDance):")
    print(f"  {ICEBERG_NAMESPACE}.{ICEBERG_TABLE_TASK_STAGE}")
    print(f"  {ICEBERG_NAMESPACE}.{ICEBERG_TABLE_CONFIG}")
    print(f"\nJob IDs returned for downstream filtering: {len(job_ids)}")
    if job_ids:
        for i, jid in enumerate(job_ids, 1):
            print(f"  {i}. {jid}")
    else:
        print(f"  ⚠ No job_ids - downstream steps will return 0 records")
    print(f"\nNext step: Run emr_serverless_recommender_expedia.py")
    print("="*80)

    return job_ids


if __name__ == '__main__':
    main()
