{
 "title": "OS Level Metrics",
 "description": "Requires Node Exporter (https://github.com/prometheus/node_exporter) to be installed on the nodes to be monitored.",
 "tags": [
  "Amazon EMR",
  "Prometheus",
  "Node_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"$job\"}, cluster_id) "
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\", cluster_id=~'$cluster'}, instance) "
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Servers Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up {job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Normalized System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', fstype!='tmpfs'}",
     "legendFormat": "Size"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"}-0",
     "legendFormat": "Available"
    },
    {
     "expr": "1- (node_filesystem_avail_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"} / node_filesystem_size_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\", cluster_id=~'$cluster',  instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~\"$instance\", fstype!=\"tmpfs\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', mode=\"idle\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum(node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Paging",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) + rate(node_vmstat_pswpout {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmission Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Receive Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (avg by (cluster_id, instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"}[1m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Normalized System Load",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_load1 {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)/count(node_cpu_seconds_total{job=\"$job\",  cluster_id=~'$cluster', instance=~'$instance', mode='system'}) by (cluster_id, instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Idle Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"idle\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"system\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "User Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"user\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IOWait Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"iowait\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Steal Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"steal\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Soft IRQ Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', mode=\"softirq\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IRQ Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance', mode=\"irq\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NICE Mode CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance', mode=\"nice\"} [$interval]))/sum by (job, cluster_id, instance)(rate(node_cpu_seconds_total {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_disk_io_time_weighted_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Merged Write I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_writes_merged_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Merged Read I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance)(rate(node_disk_reads_merged_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk I/O Request Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " ((sum by (job, cluster_id, instance)(rate(node_disk_read_bytes_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])))+(sum by (job, cluster_id, instance)(rate(node_disk_written_bytes_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))))/((sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))) + (sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval]))))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Write Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_write_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_writes_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Read Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, cluster_id, instance)(rate(node_disk_read_time_seconds_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))/(sum by (job, cluster_id, instance)(rate(node_disk_reads_completed_total {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval])))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-(sum(node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance)) / (sum(node_memory_MemTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}) by (cluster_id, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Paging",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) + rate(node_vmstat_pswpout {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Swap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-node_memory_SwapFree_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/node_memory_SwapTotal_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Commit Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes {job=\"$job\",  cluster_id=~'$cluster',instance=~'$instance'}/node_memory_CommitLimit_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OOM Kill",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": " rate(node_vmstat_oom_kill{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Up",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_network_up {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', device=~\"eth.\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Transmission Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Receive Throughput",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{device=~\"eth.\", job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transmission Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Receive Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transmission Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_errs_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Receive Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transmission Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_drop_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Receive Drop",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])/rate(node_network_transmit_packets_total{device=~\"eth.\",job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance', fstype!='tmpfs'}",
       "legendFormat": "Size"
      },
      {
       "expr": "node_filesystem_avail_bytes {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"}-0",
       "legendFormat": "Available"
      },
      {
       "expr": "1- (node_filesystem_avail_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"} / node_filesystem_size_bytes{job=\"$job\", cluster_id=~'$cluster', instance=~'$instance',fstype!=\"tmpfs\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_open_fds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}/ process_max_fds {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File System Device Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (job, cluster_id, instance) (rate(node_filesystem_device_error {job=\"$job\", cluster_id=~'$cluster', instance=~'$instance'} [$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}