{
 "title": "Spark Metrics by Components",
 "tags": [
  "spark",
  "metrics",
  "components"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app_id",
    "label": "Application ID",
    "query": {
     "query": "label_values({__name__=~\"my_application_.*\"}, __name__)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Driver - appStatus Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Jobs (appStatus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_DAGScheduler_job_activeJobs",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Running Stages (appStatus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_DAGScheduler_stage_runningStages",
     "legendFormat": "Running Stages"
    }
   ]
  },
  {
   "title": "Failed Stages (appStatus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_DAGScheduler_stage_failedStages",
     "legendFormat": "Failed Stages"
    }
   ]
  },
  {
   "title": "Total Executors (appStatus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_ExecutorAllocationManager_executors_numberAllExecutors",
     "legendFormat": "All Executors"
    }
   ]
  },
  {
   "title": "Driver - BlockManager Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "BlockManager Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_BlockManager_memory_memUsed_MB",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "my_${app_id}_driver_BlockManager_memory_maxMem_MB",
     "legendFormat": "Max Memory"
    },
    {
     "expr": "my_${app_id}_driver_BlockManager_memory_remainingMem_MB",
     "legendFormat": "Remaining Memory"
    }
   ]
  },
  {
   "title": "BlockManager Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_driver_BlockManager_disk_diskSpaceUsed_MB",
     "legendFormat": "Disk Space Used"
    }
   ]
  },
  { "title": "Executor - executor Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Succeeded Tasks (executor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_executor_succeededTasks_count",
     "legendFormat": "Executor 1"
    },
    {
     "expr": "my_${app_id}_2_executor_succeededTasks_count",
     "legendFormat": "Executor 2"
    },
    {
     "expr": "my_${app_id}_3_executor_succeededTasks_count",
     "legendFormat": "Executor 3"
    },
    {
     "expr": "my_${app_id}_4_executor_succeededTasks_count",
     "legendFormat": "Executor 4"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read (executor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_executor_shuffleTotalBytesRead_count",
     "legendFormat": "Executor 1"
    },
    {
     "expr": "my_${app_id}_2_executor_shuffleTotalBytesRead_count",
     "legendFormat": "Executor 2"
    },
    {
     "expr": "my_${app_id}_3_executor_shuffleTotalBytesRead_count",
     "legendFormat": "Executor 3"
    },
    {
     "expr": "my_${app_id}_4_executor_shuffleTotalBytesRead_count",
     "legendFormat": "Executor 4"
    }
   ]
  },
  {
   "title": "Active Tasks (executor)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_1_executor_threadpool_activeTasks",
     "legendFormat": "Executor 1"
    },
    {
     "expr": "my_${app_id}_2_executor_threadpool_activeTasks",
     "legendFormat": "Executor 2"
    },
    {
     "expr": "my_${app_id}_3_executor_threadpool_activeTasks",
     "legendFormat": "Executor 3"
    },
    {
     "expr": "my_${app_id}_4_executor_threadpool_activeTasks",
     "legendFormat": "Executor 4"
    }
   ]
  },
  {
   "title": "Executor - ExecutorMetric Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "JVM Heap Memory (ExecutorMetric)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_ExecutorMetrics_JVMHeapMemory",
     "legendFormat": "Executor 1 JVM Heap"
    },
    {
     "expr": "my_${app_id}_2_ExecutorMetrics_JVMHeapMemory",
     "legendFormat": "Executor 2 JVM Heap"
    },
    {
     "expr": "my_${app_id}_3_ExecutorMetrics_JVMHeapMemory",
     "legendFormat": "Executor 3 JVM Heap"
    },
    {
     "expr": "my_${app_id}_4_ExecutorMetrics_JVMHeapMemory",
     "legendFormat": "Executor 4 JVM Heap"
    }
   ]
  },
  {
   "title": "Major GC Time (ExecutorMetric)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_ExecutorMetrics_MajorGCTime",
     "legendFormat": "Executor 1 Major GC"
    },
    {
     "expr": "my_${app_id}_2_ExecutorMetrics_MajorGCTime",
     "legendFormat": "Executor 2 Major GC"
    },
    {
     "expr": "my_${app_id}_3_ExecutorMetrics_MajorGCTime",
     "legendFormat": "Executor 3 Major GC"
    },
    {
     "expr": "my_${app_id}_4_ExecutorMetrics_MajorGCTime",
     "legendFormat": "Executor 4 Major GC"
    }
   ]
  },
  { "title": "shuffleService Component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Shuffle Client Direct Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_ExternalShuffle_shuffle_client_usedDirectMemory",
     "legendFormat": "Executor 1 Direct Memory"
    },
    {
     "expr": "my_${app_id}_2_ExternalShuffle_shuffle_client_usedDirectMemory",
     "legendFormat": "Executor 2 Direct Memory"
    },
    {
     "expr": "my_${app_id}_3_ExternalShuffle_shuffle_client_usedDirectMemory",
     "legendFormat": "Executor 3 Direct Memory"
    },
    {
     "expr": "my_${app_id}_4_ExternalShuffle_shuffle_client_usedDirectMemory",
     "legendFormat": "Executor 4 Direct Memory"
    }
   ]
  },
  {
   "title": "Shuffle Client Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_${app_id}_1_ExternalShuffle_shuffle_client_usedHeapMemory",
     "legendFormat": "Executor 1 Heap Memory"
    },
    {
     "expr": "my_${app_id}_2_ExternalShuffle_shuffle_client_usedHeapMemory",
     "legendFormat": "Executor 2 Heap Memory"
    },
    {
     "expr": "my_${app_id}_3_ExternalShuffle_shuffle_client_usedHeapMemory",
     "legendFormat": "Executor 3 Heap Memory"
    },
    {
     "expr": "my_${app_id}_4_ExternalShuffle_shuffle_client_usedHeapMemory",
     "legendFormat": "Executor 4 Heap Memory"
    }
   ]
  },
  { "title": "applicationMaster Component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Running Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_applicationMaster_numExecutorsRunning",
     "legendFormat": "Running Executors"
    }
   ]
  },
  {
   "title": "Failed Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_${app_id}_applicationMaster_numExecutorsFailed",
     "legendFormat": "Failed Executors"
    }
   ]
  },
  {
   "title": "Container & Task Management",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "my_${app_id}_applicationMaster_numContainersPendingAllocate",
     "legendFormat": "Pending Containers"
    },
    {
     "expr": "my_${app_id}_applicationMaster_numReleasedContainers",
     "legendFormat": "Released Containers"
    },
    {
     "expr": "my_${app_id}_applicationMaster_numLocalityAwareTasks",
     "legendFormat": "Locality Aware Tasks"
    }
   ]
  }
 ]
}