apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: "true"
  name: spark-driver-monitoring
  namespace: emr
spec:
  jobLabel: spark-driver-monitoring
  namespaceSelector:
    matchNames:
      - emr
  podMetricsEndpoints:
    - port: "web-ui"
      path: /metrics/executors/prometheus/
  selector:
    matchLabels:
      spark-role: driver
      emr-containers.amazonaws.com/resource.type: job.run

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: "true"
  name: spark-service-monitoring
  namespace: emr
spec:
  namespaceSelector:
    matchNames:
      - emr
  endpoints:
    - port: "web-ui"
      path: /metrics/driver/prometheus/
  selector:
    matchLabels:
      spark_role: driver
      emr-containers.amazonaws.com/resource.type: job.run
