create user rangeradmin with createdb login password 'rangeradmin';
create database ranger with owner rangeradmin;
GRANT ALL PRIVILEGES ON SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rangeradmin;
ALTER ROLE rangeradmin IN DATABASE ranger SET tcp_keepalives_idle TO '60';
ALTER ROLE rangeradmin IN DATABASE ranger SET tcp_keepalives_interval TO '10';
ALTER ROLE rangeradmin IN DATABASE ranger SET tcp_keepalives_count TO '3';
ALTER ROLE postgres IN DATABASE postgres SET tcp_keepalives_idle TO '60';
ALTER ROLE postgres IN DATABASE postgres SET tcp_keepalives_interval TO '10';
ALTER ROLE postgres IN DATABASE postgres SET tcp_keepalives_count TO '3';
