#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
    # log4j.logger.io.grpc.netty.NettyServerHandler=ALL
    # log4j.logger.io.grpc.netty.NettyClientHandler=ALL
    
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rss-configuration
  namespace: uniffle
data:
  coordinator.conf: |-
    rss.coordinator.app.expired 60000
    rss.coordinator.exclude.nodes.file.path /data/rssadmin/rss/coo
    rss.coordinator.server.heartbeat.timeout 30000
    rss.jetty.http.port 19996
    rss.rpc.server.port 19997
    rss.coordinator.select.partition.strategy CONTINUOUS
  log4j.properties: |-
    log4j.rootCategory=WARN, RollingAppender
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.Threshold=WARN
    log4j.appender.console.target=System.err
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
    log4j.appender.RollingAppender=org.apache.log4j.RollingFileAppender
    log4j.appender.RollingAppender.File=./logs/rss.log
    log4j.appender.RollingAppender.MaxFileSize=50MB
    log4j.appender.RollingAppender.MaxBackupIndex=10
    log4j.appender.RollingAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.RollingAppender.layout.ConversionPattern=[%p] %d %t %c{1} %M - %m%n
  server.conf: |-
    rss.coordinator.quorum rss-coordinator-uniffle-rss-0:19997,rss-coordinator-uniffle-rss-1:19997
    rss.jetty.http.port 19996
    rss.rpc.executor.size 2000
    rss.rpc.message.max.size 1073741824
    rss.rpc.server.port 19997
    rss.server.app.expired.withoutHeartbeat 120000
    rss.server.buffer.capacity 87g
    rss.server.commit.timeout 600000
    rss.server.disk.capacity -1
    rss.server.event.size.threshold.l1 64m
    rss.server.event.size.threshold.l2 128m
    rss.server.event.size.threshold.l3 192m

    # For huge partitions
    rss.server.flush.cold.storage.threshold.size 64m
    rss.server.single.buffer.flush.threshold 65m
    rss.server.max.concurrency.of.single.partition.writer 20
    rss.server.huge-partition.size.threshold 20g
    rss.server.huge-partition.memory.limit.ratio 0.2
    rss.server.flush.thread.alive 6
    rss.server.flush.threadPool.size 12

    rss.server.hadoop.dfs.client.socket-timeout 15000
    rss.server.hadoop.dfs.replication 1
    rss.server.hdfs.base.path hdfs://hdfs-namenode-0.hdfs-namenodes/rss1/rssdata,hdfs://hdfs-namenode-0.hdfs-namenodes/rss2/rssdata
    rss.server.health.check.enable false
    rss.server.heartbeat.interval 10000
    rss.server.heartbeat.timeout 60000
    rss.server.memory.shuffle.highWaterMark.percentage 70.0
    rss.server.memory.shuffle.lowWaterMark.percentage 10.0
    rss.server.pending.event.timeoutSec 600
    rss.server.preAllocation.expired 120000
    rss.server.read.buffer.capacity 29g
    rss.server.shuffle.expired.timeout.ms 120000
    rss.server.write.retry.max 2
    rss.storage.basePath /rss1/rssdata,/rss2/rssdata
    rss.storage.type MEMORY_LOCALFILE
    rss.server.cleanup.threshold 80.0