#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
apiVersion: uniffle.apache.org/v1alpha1
kind: RemoteShuffleService
metadata:
  name: uniffle-rss
  namespace: uniffle
spec: 
  configMapName: rss-configuration
  coordinator:
    nodeSelector:
      app: css   
    image: 021732063925.dkr.ecr.us-east-1.amazonaws.com/uniffle-server:0.7.0-snapshot
    initContainerImage: "busybox:latest"
    rpcNodePort:
      - 30001
      - 30011
    httpNodePort:
      - 30002
      - 30012
    xmxSize: 16G
    configDir: "/data/rssadmin/rss/conf"
    replicas: 1
    excludeNodesFilePath: "/data/rssadmin/rss/coo/exclude_nodes"
    securityContext:
      runAsUser: 999
      fsGroup: 1000
    logHostPath: "/data/logs/rss/coordinator"
    hostPathMounts:
      /data/logs/rss/coordinator: /data/rssadmin/rss/logs 
  shuffleServer:
    sync: true
    upgradeStrategy:
      type: FullRestart
    nodeSelector:
      app: css
    replicas: 3
    image: 021732063925.dkr.ecr.us-east-1.amazonaws.com/uniffle-server:0.7.0-snapshot 
    initContainerImage: "busybox:latest"
    xmxSize: 144G
    configDir: "/data/rssadmin/rss/conf"
    securityContext:
      runAsUser: 999
      fsGroup: 1000
    logHostPath: "/data/logs/rss/shuffle-server"
    hostPathMounts:
      /data/logs/rss/shuffle-server: /data/rssadmin/rss/logs
      # /local* is EC2 SSD disk name. /rss* is a local directory created by InitContianer 
      /local1: /rss1
      /local2: /rss2