{{- if  .Values.engine.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark
  namespace: {{ .Values.engine.namespace }}
  labels:
    {{- include "kyuubi.labels" . | nindent 4 }}
data:
  {{- with .Values.sparkConf.sparkEnv }}
  spark-env.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.sparkConf.sparkDefaults }}
  spark-defaults.conf: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.sparkConf.log4j2 }}
  log4j2.properties: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.sparkConf.metrics }}
  metrics.properties: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
{{- if (.Files.Glob "security/*") }}
{{ (.Files.Glob "security/*").AsConfig | indent 2 }}
{{- end }} 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.engine.namespace }}
  labels:
    {{- include "kyuubi.labels" . | nindent 4 }}
data:
  {{- with .Values.kyuubiConf.kyuubiEnv }}
  kyuubi-env.sh: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  kyuubi-defaults.conf: |
    ## Helm chart provided Kyuubi configurations
    kyuubi.kubernetes.namespace={{ .Release.Namespace }}
    kyuubi.frontend.connection.url.use.hostname=false
    kyuubi.frontend.thrift.binary.bind.port={{ .Values.server.thriftBinary.port }}
    kyuubi.frontend.thrift.http.bind.port={{ .Values.server.thriftHttp.port }}
    kyuubi.frontend.rest.bind.port={{ .Values.server.rest.port }}
    kyuubi.frontend.mysql.bind.port={{ .Values.server.mysql.port }}
    kyuubi.frontend.protocols={{ include "kyuubi.frontend.protocols" . }}

    # Kyuubi Metrics
    kyuubi.metrics.enabled={{ .Values.monitoring.prometheus.enabled }}
    kyuubi.metrics.reporters={{ .Values.metricsReporters }}

    ## User provided Kyuubi configurations
    {{- with .Values.kyuubiConf.kyuubiDefaults }}
      {{- tpl . $ | nindent 4 }}
    {{- end }}
  {{- with .Values.kyuubiConf.log4j2 }}
  log4j2.xml: |
    {{- tpl . $ | nindent 4 }}
{{- end }}
{{- end }}

