{
 "title": "HBase",
 "description": "HBase dashboard",
 "tags": [
  "hbase",
  "emr"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(hadoop_hbase_exceptions, instance)"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "label_values(hbase_metric_memstoresize, table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_numregionservers{cluster=\"$cluster\"}",
     "legendFormat": "Region Servers"
    },
    {
     "expr": "hadoop_hbase_numdeadregionservers{cluster=\"$cluster\"}",
     "legendFormat": "Dead Region Servers"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hadoop_hbase_blockcachecounthitpercent{cluster=\"$cluster\"})",
     "legendFormat": "BlockCache Hit Ratio"
    },
    {
     "expr": "avg(hadoop_hbase_l1cachehitratio{cluster=\"$cluster\"})",
     "legendFormat": "L1 Hit Ratio"
    },
    {
     "expr": "avg(hadoop_hbase_l2cachehitratio{cluster=\"$cluster\"})",
     "legendFormat": "L2 Hit Ratio"
    }
   ]
  },
  {
   "title": "Cluster Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_readrequestrate{cluster=\"$cluster\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(hadoop_hbase_writerequestrate{cluster=\"$cluster\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_hbase_masteractivetime{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_hbase_masteractivetime{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total vCPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{cluster=~\"$cluster\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_numregions{cluster=\"$cluster\"})",
     "legendFormat": "Total Regions"
    },
    {
     "expr": "sum(hadoop_hbase_ritcount{cluster=\"$cluster\"})",
     "legendFormat": "Regions In Transition (RIT)"
    },
    {
     "expr": "hadoop_hbase_ritcountoverthreshold{cluster=\"$cluster\"}",
     "legendFormat": "RIT over Threshold"
    }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "hadoop_hbase_storefilecount{cluster=\"$cluster\"}"
    },
    {
     "expr": "hadoop_hbase_storefilesize{cluster=\"$cluster\"}"
    },
    {
     "expr": "hadoop_hbase_numregions{cluster=\"$cluster\"}"
    },
    {
     "expr": "hadoop_hbase_writerequestrate{cluster=\"$cluster\"}"
    },
    {
     "expr": "hadoop_hbase_readrequestrate{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_totalrequestcount{cluster=\"$cluster\"})",
     "legendFormat": "Total Request Count"
    },
    {
     "expr": "sum(hadoop_hbase_readrequestcount{cluster=\"$cluster\"})",
     "legendFormat": "Read Request Count"
    },
    {
     "expr": "sum(hadoop_hbase_writerequestcount{cluster=\"$cluster\"})",
     "legendFormat": "Write Request Count"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps", "label": "Requests Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_hbase_readrequestrate{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(hadoop_hbase_writerequestrate{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Region Server / Read Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_readrequestrate{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance}}"
    },
    {
     "expr": "sum(hadoop_hbase_readrequestrate{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Region Server / Write Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "hadoop_hbase_writerequestrate{cluster=\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(hadoop_hbase_writerequestrate{cluster=\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds{instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - 1m"
      },
      {
       "expr": "node_load5{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - 5m"
      },
      {
       "expr": "node_load15{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - 15m"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "CPU IOwait",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[30m])) * 100"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[30m])) by (instance)",
       "legendFormat": "{{instance}} - System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[30m])) by (instance)",
       "legendFormat": "{{instance}} - User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[30m])) by (instance)",
       "legendFormat": "{{instance}} - Iowait"
      },
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[30m])) by (instance)",
       "legendFormat": "{{instance}} - Total"
      }
     ]
    },
    {
     "title": "Open  File Descriptor / Context switches",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - filefd"
      },
      {
       "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - switches"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - Avaliable"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Node traffic in bits/sec",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}} - {{device}} in"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}} - {{device}} out"
      }
     ]
    },
    {
     "title": "Disk Space Used (EXT4/XFS)",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"}-0"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext4|xfs\"}-0"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"})"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs\"})",
       "legendFormat": "{{instance}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/Os Time",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - IO time"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "description": "Disk throughput in bytes/sec",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      {
       "format": "Bps",
       "label": "Throughput Read (-) / Write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "description": "Read/write completions per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "iops", "label": "IO Read (-) / Write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[30m]) ",
       "legendFormat": "{{instance}} - {{device}} - Write"
      }
     ]
    },
    {
     "title": "TCP Sockets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$instance'}",
       "legendFormat": "{{instance}} - TCP Allocated"
      },
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$instance'}",
       "legendFormat": "{{instance}} - TCP Established"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~'$instance'}",
       "legendFormat": "{{instance}} - TCP Used"
      }
     ]
    },
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "s", "label": "Time Read (-) / Write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - Read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[30m])",
       "legendFormat": "{{instance}} - {{device}} - Write"
      }
     ]
    }
   ]
  },
  {
   "title": "WALs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistics",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hadoop_hbase_hlogfilecount{cluster=\"$cluster\"})",
       "legendFormat": "(HDFS) WALs Count"
      },
      {
       "expr": "sum(hadoop_hbase_hlogfilesize{cluster=\"$cluster\"})",
       "legendFormat": "(HDFS) WALs Size "
      }
     ]
    },
    {
     "title": "WALs Size (HDFS)",
     "type": "graph",
     "description": "Size of all WAL Files",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_hlogfilesize{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "WALs Count (HDFS)",
     "type": "graph",
     "description": "Number of WAL Files",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_hlogfilecount{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Slow Append Rate",
     "type": "graph",
     "description": "Number of slow appends",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_slowappendcount{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storefiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statistics",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hadoop_hbase_storefilecount{cluster=\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Storefiles Count"
      },
      {
       "expr": "sum(hadoop_hbase_storefilesize{cluster=\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Storefiles Size"
      }
     ]
    },
    {
     "title": "Store File Size",
     "type": "graph",
     "description": "The total size of the store files (data files) in the RegionServer",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_storefilesize{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Root Index Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_storefileindexsize{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_staticindexsize{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Bloom Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_staticbloomsize{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstore Size",
     "type": "graph",
     "description": "The total Memstore memory size of the RegionServer",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_memstoresize{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Flushed Cells Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_flushedcellscount{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes compacted",
     "type": "graph",
     "description": "Sum of filesize on all files entering a finished, successful or aborted, compaction",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numbytescompactedcount{cluster=\"$cluster\",instance=~\"$instance\",table=~\"$table\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "(Table) Bytes compacted ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numbytescompactedcount{cluster=\"$cluster\",instance=~\"$instance\",table=~\"$table\"}[1m])) by (table)",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "(Region Server) Bytes compacted ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numbytescompactedcount{cluster=\"$cluster\",instance=~\"$instance\",table=~\"$table\"}[1m])) by (instance, instance_private_ip)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Compaction Queue Length",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_compactionqueuelength{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "(Table) Compactions completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_compactionscompletedcount{instance=~\"$instance\",table=~\"$table\"}[1m])) by (table)",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "(Region Server) Compactions completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_compactionscompletedcount{instance=~\"$instance\",table=~\"$table\"}[1m])) by (instance, instance_private_ip)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Files compacted",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numfilescompactedcount{instance=~\"$instance\",table=~\"$table\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "(Table) Files compacted ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numfilescompactedcount{instance=~\"$instance\",table=~\"$table\"}[1m])) by (table)",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "(Region Server) Files compacted",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hbase_metric_numfilescompactedcount{instance=~\"$instance\",table=~\"$table\"}[1m])) by (instance,instance_private_ip)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Major compacted cells count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hadoop_hbase_majorcompactedcellscount{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Major compacted cells count /  instance",
     "type": "graph",
     "description": "rate ",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hadoop_hbase_majorcompactedcellscount{cluster=\"$cluster\",instance=~\"$instance\"}[1m])) by (instance,instance_private_ip)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Major compacted cells size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hadoop_hbase_majorcompactedcellssize{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Major compacted cells size / instance",
     "type": "graph",
     "description": "rate",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 54 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hadoop_hbase_majorcompactedcellssize{cluster=\"$cluster\",instance=~\"$instance\"}[1m])) by (instance,instance_private_ip)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "APPEND Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_append_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum(rate(hadoop_append_scan_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "INCREMENT Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_increment_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum(rate(hadoop_hbase_increment_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "GET Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37 },
     "repeat": "num_ops",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_get_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum(rate(hadoop_hbase_get_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "PUT Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_putbatch_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum(rate(hadoop_hbase_putbatch_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "SCAN Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_scantime_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(hadoop_hbase_scantime_num_ops{cluster=\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "APPEND Latency",
     "type": "graph",
     "description": "Values equals to zero indicates responses occurs under the millisencond",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_append_max{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "hadoop_hbase_append_mean{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - mean"
      },
      {
       "expr": "hadoop_hbase_append_min{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - min"
      },
      {
       "expr": "hadoop_hbase_append_99th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 99th"
      },
      {
       "expr": "hadoop_hbase_append_95th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 95th"
      },
      {
       "expr": "hadoop_hbase_append_75th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 75th"
      },
      {
       "expr": "hadoop_hbase_append_25th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 25th"
      }
     ]
    },
    {
     "title": "INCREMENT Latency",
     "type": "graph",
     "description": "Values equals to zero indicates responses occurs under the millisencond",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_increment_max{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "hadoop_hbase_increment_mean{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - mean"
      },
      {
       "expr": "hadoop_hbase_increment_min{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - min"
      },
      {
       "expr": "hadoop_hbase_increment_99th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 99th"
      },
      {
       "expr": "hadoop_hbase_increment_95th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 95th"
      },
      {
       "expr": "hadoop_hbase_increment_75th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 75th"
      },
      {
       "expr": "hadoop_hbase_increment_25th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 25th"
      }
     ]
    },
    {
     "title": "GET Latency",
     "type": "graph",
     "description": "Values equals to zero indicates responses occurs under the millisencond",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_get_max{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "hadoop_hbase_get_mean{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - mean"
      },
      {
       "expr": "hadoop_hbase_get_min{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - min"
      },
      {
       "expr": "hadoop_hbase_get_99th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 99th"
      },
      {
       "expr": "hadoop_hbase_get_95th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 95th"
      },
      {
       "expr": "hadoop_hbase_get_75th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 75th"
      },
      {
       "expr": "hadoop_hbase_get_25th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 25th"
      }
     ]
    },
    {
     "title": "PUT Latency",
     "type": "graph",
     "description": "Values equals to zero indicates responses occurs under the millisencond",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_putbatch_max{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "hadoop_hbase_putbatch_mean{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - mean"
      },
      {
       "expr": "hadoop_hbase_putbatch_min{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - min"
      },
      {
       "expr": "hadoop_hbase_putbatch_99th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 99th"
      },
      {
       "expr": "hadoop_hbase_putbatch_95th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 95th"
      },
      {
       "expr": "hadoop_hbase_putbatch_75th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 75th"
      },
      {
       "expr": "hadoop_hbase_putbatch_25th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 25th"
      }
     ]
    },
    {
     "title": "SCAN Latency",
     "type": "graph",
     "description": "Values equals to zero indicates responses occurs under the millisencond",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_scantime_max{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - max"
      },
      {
       "expr": "hadoop_hbase_scantime_mean{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - mean"
      },
      {
       "expr": "hadoop_hbase_scantime_min{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - min"
      },
      {
       "expr": "hadoop_hbase_scantime_99th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 99th"
      },
      {
       "expr": "hadoop_hbase_scantime_95th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 95th"
      },
      {
       "expr": "hadoop_hbase_scantime_75th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 75th"
      },
      {
       "expr": "hadoop_hbase_scantime_25th_percentile{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - 25th"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Nodes",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "hadoop_hbase_memheapmaxm{cluster=\"$cluster\",instance=~\"$instance\"}"
      },
      {
       "expr": "hadoop_hbase_memheapusedm{cluster=\"$cluster\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "description": "Total GC count",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gccount{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC ParNew Count",
     "type": "graph",
     "description": "hadoop_hbase_gccountparnew",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gccountparnew{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC Concurrent Mark Sweep Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gccountconcurrentmarksweep{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "description": "hadoop_hbase_gctimemillis  rate",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gctimemillis{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC ParNew Time",
     "type": "graph",
     "description": "hadoop_hbase_gctimemillisparnew  rate",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gctimemillisparnew{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "GC Concurrent Mark Sweep Time",
     "type": "graph",
     "description": "hadoop_hbase_gctimemillisconcurrentmarksweep  rate",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_gctimemillisconcurrentmarksweep{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Hottest Node - heap (used)",
     "type": "graph",
     "description": "green line should be below yellow",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "max(hadoop_hbase_memheapusedm{instance=~\"$instance\"})",
       "legendFormat": "Hottest Node"
      },
      {
       "expr": "max(hadoop_hbase_memheapcommittedm{instance=~\"$instance\"})",
       "legendFormat": "Max Allowed"
      }
     ]
    },
    {
     "title": "Memory heap (used)",
     "type": "graph",
     "description": "Memory heap (used)",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_memheapusedm{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory heap (committed)",
     "type": "graph",
     "description": "Memory heap (committed)",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_memheapcommittedm{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Threads Deadlocked",
     "type": "graph",
     "description": "Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_deadlocked{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory non-heap (used)",
     "type": "graph",
     "description": "Current non-heap memory used",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_memnonheapusedm{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory non-heap (committed)",
     "type": "graph",
     "description": "Current non-heap memory committed",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "hadoop_hbase_memnonheapcommittedm{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Threads Count",
     "type": "graph",
     "description": "Current thread count of a JVM\ngauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{cluster=\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions",
     "type": "graph",
     "description": "Reports Region Servers with exceptions. Useful to quickly locate a RS with an issue",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Not Serving Region",
     "type": "graph",
     "description": "Thrown by a region server if it is sent a request for a region it is not serving.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_multiresponsetoolarge{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Region Moved",
     "type": "graph",
     "description": "Subclass if the server knows the region is now on another server. This allows the client to call the new region server without calling the master.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_regionmovedexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Region Too Busy",
     "type": "graph",
     "description": "Thrown by a region server if it will block and wait to serve a request. For example, the client wants to insert something to a region while the region is compacting.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_regiontoobusyexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Call Queue Too Big",
     "type": "graph",
     "description": "Thrown by a region server when receiving more requests of what it can handle",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_callqueuetoobig{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Failed Sanity Check",
     "type": "graph",
     "description": "Exception thrown if a mutation fails sanity checks.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_failedsanitycheckexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Multi Response Too Large",
     "type": "graph",
     "description": "Exception thrown when response is too long",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_multiresponsetoolarge{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Out Of Order Scanner Next",
     "type": "graph",
     "description": "Thrown by a RegionServer while doing next() calls on a ResultScanner. Both client and server maintain a nextCallSeq and if they do not match, RS will throw this exception.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_outoforderscannernextexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Scanner Reset",
     "type": "graph",
     "description": "Thrown when the server side has received an Exception, and asks the Client to reset the scanner state by closing the current region scanner, and reopening from the start of last seen row.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_scannerresetexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Unknown Scanner",
     "type": "graph",
     "description": "Thrown if a region server is passed an unknown scanner id. Usually means the client has take too long between checkins and so the scanner lease on the serverside has expired OR the serverside is closing down and has cancelled all leases.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(hadoop_hbase_exceptions_unknownscannerexception{cluster=\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}